version: '3.1'
services:
    postgres:
        image: 'postgres:13.3'
        working_dir: /application
        volumes:
            - '${APP_DIR}:/application'
        environment:
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_DATABASE}'
        ports:
             - '${DB_PORT:-5432}:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '${APP_DIR}:/application'
            - './config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '${WEBSERVER_PORT:-8080}:80'

    php-fpm:
        build: config/php-fpm/prod
        working_dir: /application
        volumes:
            - '${APP_DIR}:/application'
            - './config/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
